-- create database sausage --

USE Twitter_Trend

CREATE TABLE tblTWEET 
(TweetID INT IDENTITY(1, 1) primary key NOT NULL,
Content varchar(140) NOT NULL,
UserID INT FOREIGN KEY REFERENCES tblUSER(UserID) NOT NULL,
EventID INT FOREIGN KEY REFERENCES tblTWEET_EVENT(EventID) NOT NULL,
TopicTypeID INT FOREIGN KEY REFERENCES tblTopicType(TopicTypeID) NOT NULL,
Date_Time DATE DEFAULT GetDate() NOT NULL,
LocationID INT FOREIGN KEY REFERENCES tblLOCATION(LocationID) NOT NULL
)

CREATE TABLE tblUSER
(UserID INT IDENTITY(1,1) primary key NOT NULL, 
DisplayName VARCHAR(20) NOT NULL,
Bio VARCHAR(140),
Banner VARCHAR(100),
Icon VARCHAR(100) NOT NULL,
DateJoined DATE DEFAULT GetDate() NOT NULL
)

CREATE TABLE tblUSER_EVENT
(UserEventID INT IDENTITY(1,1) primary key NOT NULL,
UserEventTypeID INT FOREIGN KEY REFERENCES tblUSER_EVENT_TYPE(UserEventTypeID) NOT NULL,
UserID1 INT FOREIGN KEY REFERENCES tblUSER(UserID) NOT NULL,
UserID2 INT FOREIGN KEY REFERENCES tblUSER(UserID) NOT NULL,
Date_Time DATE DEFAULT GetDate() NOT NULL
)

CREATE TABLE tblUSER_EVENT_TYPE
(UserEventTypeID INT IDENTITY(1,1) primary key NOT NULL,
UserEventTypeName VARCHAR(20) NOT NULL,
UserEventTypeDescr VARCHAR(100)
)

CREATE TABLE tblTWEET_EVENT
(EventID INT IDENTITY(1,1) primary key NOT NULL,
EventTypeID INT FOREIGN KEY REFERENCES tblTWEET_EVENT_TYPE(EventTypeID) NOT NULL,
EventName VARCHAR(20) NOT NULL,
EventNameDescr VARCHAR(100)
)

CREATE TABLE tblTWEET_EVENT_TYPE 
(EventTypeID INT IDENTITY(1,1) primary key NOT NULL,
EventTypeName VARCHAR(20) NOT NULL,
EventTypeDescr VARCHAR(100)
)

CREATE TABLE tblLOCATION
(LocationID INT IDENTITY(1,1) primary key NOT NULL,
LocationName VARCHAR(100)
)

CREATE TABLE tblTWEET_HASHTAG
(HashtagID INT FOREIGN KEY REFERENCES tblHASHTAG(HashtagID) NOT NULL,
TweetID INT FOREIGN KEY REFERENCES tblTWEET(TweetID) NOT NULL
)

CREATE TABLE tblHASHTAG
(HashtagID INT IDENTITY(1,1) primary key NOT NULL,
HashtagName VARCHAR(140) NOT NULL
)

CREATE TABLE tblTopicType
(TopicTypeID INT IDENTITY(1,1) primary key NOT NULL,
TopicTypeName VARCHAR(50)
)

CREATE TABLE tblATTACHMENT 
(AttachmentID INT IDENTITY(1,1) primary key NOT NULL,
AttachmentTypeID INT FOREIGN KEY REFERENCES tblATTACHMENT_TYPE(AttachmentTypeID) NOT NULL,
TweetID INT FOREIGN KEY REFERENCES tblTWEET(TweetID) NOT NULL,
Link VARCHAR(200) NOT NULL
)

CREATE TABLE tblATTACHMENT_TYPE
(AttachmentTypeID INT IDENTITY(1,1) primary key NOT NULL,
AttachmentTypeName VARCHAR(20) NOT NULL
)







